export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";

export const GET_ALMONDS_REQUEST = "GET_ALMONDS_REQUEST";
export const GET_ALMONDS_SUCCESS = "GET_ALMONDS_SUCCESS";
export const GET_ALMONDS_FAIL = "GET_ALMONDS_FAIL";

export const GET_ALMOND_DETAILS_REQUEST = "GET_ALMOND_DETAILS_REQUEST";
export const GET_ALMOND_DETAILS_SUCCESS = "GET_ALMOND_DETAILS_SUCCESS";
export const GET_ALMOND_DETAILS_FAIL = "GET_ALMOND_DETAILS_FAIL";
export const GET_ALMOND_DETAILS_RESET = "GET_ALMOND_DETAILS_RESET";


export const GET_CASHEWNUTS_REQUEST = "GET_CASHEWNUTS_REQUEST";
export const GET_CASHEWNUTS_SUCCESS = "GET_CASHEWNUTS_SUCCESS";
export const GET_CASHEWNUTS_FAIL = "GET_CASHEWNUTS_FAIL";

export const GET_CASHEWNUT_DETAILS_REQUEST = "GET_CASHEWNUT_DETAILS_REQUEST";
export const GET_CASHEWNUT_DETAILS_SUCCESS = "GET_CASHEWNUT_DETAILS_SUCCESS";
export const GET_CASHEWNUT_DETAILS_FAIL = "GET_CASHEWNUT_DETAILS_FAIL";
export const GET_CASHEWNUT_DETAILS_RESET = "GET_CASHEWNUT_DETAILS_RESET";

export const GET_PISTAS_REQUEST = "GET_PISTAS_REQUEST";
export const GET_PISTAS_SUCCESS = "GET_PISTAS_SUCCESS";
export const GET_PISTAS_FAIL = "GET_PISTAS_FAIL";

export const GET_PISTA_DETAILS_REQUEST = "GET_PISTA_DETAILS_REQUEST";
export const GET_PISTA_DETAILS_SUCCESS = "GET_PISTA_DETAILS_SUCCESS";
export const GET_PISTA_DETAILS_FAIL = "GET_PISTA_DETAILS_FAIL";
export const GET_PISTA_DETAILS_RESET = "GET_PISTA_DETAILS_RESET";

export const GET_FIGS_REQUEST = "GET_FIGS_REQUEST";
export const GET_FIGS_SUCCESS = "GET_FIGS_SUCCESS";
export const GET_FIGS_FAIL = "GET_FIGS_FAIL";

export const GET_FIG_DETAILS_REQUEST = "GET_FIG_DETAILS_REQUEST";
export const GET_FIG_DETAILS_SUCCESS = "GET_FIG_DETAILS_SUCCESS";
export const GET_FIG_DETAILS_FAIL = "GET_FIG_DETAILS_FAIL";
export const GET_FIG_DETAILS_RESET = "GET_FIG_DETAILS_RESET";


export const GET_RAISINS_REQUEST = "GET_RAISINS_REQUEST";
export const GET_RAISINS_SUCCESS = "GET_RAISINS_SUCCESS";
export const GET_RAISINS_FAIL = "GET_RAISINS_FAIL";

export const GET_RAISIN_DETAILS_REQUEST = "GET_RAISIN_DETAILS_REQUEST";
export const GET_RAISIN_DETAILS_SUCCESS = "GET_RAISIN_DETAILS_SUCCESS";
export const GET_RAISIN_DETAILS_FAIL = "GET_RAISIN_DETAILS_FAIL";
export const GET_RAISIN_DETAILS_RESET = "GET_RAISIN_DETAILS_RESET";